installation-template: update log function

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,7 +14,7 @@ function log() {
 	executable=$(cd $(dirname $0) && pwd)/$0
 	[[ $syslogServer != 0 ]] && syslogServerArg="-n $syslogServer --tcp"
 	tag="executable={{ $executable }} | executionId={{ $executionId }}"
-	logger -p $priority $t "$tag" $syslogServerArg "$1"
+	logger -p $priority -t "$tag" $syslogServerArg "$1"
 }
 
 while [[ $# -gt 0 ]]
@@ -30,7 +30,7 @@ do
 			syslogServer=$2
 			shift ; shift ;;
 		*)
-			echo "invalid argument: $1"
+			echo "invalid argument: $1" > &2
 			exit 1
 	esac
 done
